[package]
name = "monkey-lexer"
description = "a lexer for monkey lang"
edition = '2024'

[lib]
name = "lexer"
path= "lib.rs"

[[bin]]
name = "monkey-lexer"
path = "main.rs"

[dependencies]
serde = {version = "1.0.228", features = ["derive"]}
serde_json = "1.0.149"
insta = "1.46.3"
